name: Build and Publish Images

on:
  push:
    branches: ['main']
    paths:
      - 'whisper-cpp/**'
      - 'wyoming-api/**'
      - '.env'
      - '.github/workflows/publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env file
        # This one-liner parses the .env and sets them as actual environment variables
        run: |
          grep -v '^#' .env | grep -v '^[[:space:]]*$' >> $GITHUB_ENV

      # 2. Generate a version for the API based on current date
      - name: Generate API Version
        id: api_ver
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Whisper Image
      - name: Build Whisper-CPP
        uses: docker/build-push-action@v5
        with:
          context: ./whisper-cpp
          push: true
          platforms: linux/amd64
          build-args: |
            WHISPER_LANG=${{ env.WHISPER_LANG }}
            WHISPER_BEAM_SIZE=${{ env.WHISPER_BEAM_SIZE }}
            WHISPER_MODEL=${{ env.WHISPER_MODEL }}
            WHISPER_PROMPT=${{ env.WHISPER_PROMPT }}
            WHISPER_CPP_VERSION=${{ env.WHISPER_CPP_VERSION }}
            OPENVINO_TGZ=${{ env.OPENVINO_TGZ }}
            OPENVINO_DIR_NAME=${{ env.OPENVINO_DIR_NAME }}
            OPENVINO_URL=${{ env.OPENVINO_URL }}
          tags: |
            ghcr.io/kelvtech-co-uk/ha-whisper-cpp:${{ env.WHISPER_CPP_VERSION }}
            ghcr.io/kelvtech-co-uk/ha-whisper-cpp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. Build Wyoming-API Image
      - name: Build Wyoming-API
        uses: docker/build-push-action@v5
        with:
          context: ./wyoming-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/kelvtech-co-uk/ha-wyoming-api:${{ steps.api_ver.outputs.VERSION }}
            ghcr.io/kelvtech-co-uk/ha-wyoming-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max